<?php include("header.php"); ?>

<div class="ui text container">
<h1 class="header">Terms of Use</h1>
<strong>1. Your Acceptance</strong> 
<br>BY USING AND/OR VISITING THIS WEBSITE (collectively, including all Content available through the squareBracket.com domain name, the "squareBracket Website", or "Website"), YOU SIGNIFY YOUR ASSENT TO BOTH THESE TERMS AND CONDITIONS (the "Terms of Service") AND THE TERMS AND CONDITIONS OF squareBracket'S PRIVACY POLICY, WHICH ARE PUBLISHED AT www.squareBracket.com/privacy.php, AND WHICH ARE INCORPORATED HEREIN BY REFERENCE. If you do not agree to any of these terms, please do not use the squareBracket Website. 

<br><br><strong>2. squareBracket Website</strong> 
<br>These Terms of Service apply to all users of the squareBracket Website, including users who are also contributors of video content, information and other materials or services on the Website. The squareBracket Website may contain links to third party websites that are not owned or controlled by squareBracket. squareBracket has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party websites. In addition, squareBracket will not and cannot censor or edit the content of any third-party site. By using the Website, you expressly relieve squareBracket from any and all liability arising from your use of any third-party website. Accordingly, we encourage you to be aware when you leave the squareBracket Website, and to read the terms and conditions and privacy policy of each other website that you visit. 

<br><br><strong>3. Website Access </strong>
<br>A. squareBracket hereby grants you permission to use the Website as set forth in this Terms of Service, provided that: (i) your use of the Website as permitted is solely for your personal, noncommercial use; (ii) you will not copy or any part of the Website in any medium without squareBracket's prior written authorization; (iii) you will not alter or modify any part of the Website other than as may be reasonably necessary to use the Website for its intended purpose; and (iv) you will otherwise comply with the terms and conditions of these Terms of Service.   

<br><br>B. In order to access some features of the Website, you will have to create an account.  You may never use another's account without permission.  When creating your account, you must provide accurate and complete information.  you are solely responsible for the activity that occurs on your account, and you must keep your account password secure.  you must notify squareBracket immediately of any breach of security or unauthorized use of your account.  Although squareBracket will not be liable for your losses caused by any unauthorized use of your account, you may be liable for the losses of squareBracket or others due to such unauthorized use.

<br><br>C. You agree not to use or launch any automated system, including without limitation "robots," "spiders," "offline readers," etc that accesses the Website in a manner that sends more request messages to the squareBracket servers in a given period of time than a human can reasonably produce in the same period by using a convention on-line web browser.    Notwithstanding the foregoing, squareBracket grants the operators of public search engines permission to use spiders to copy materials from the site for the sole purpose of creating publicly available searchable indices of the materials, but not caches or archives of such materials.  squareBracket reserves the right to revoke these exceptions either generally or in specific cases.

<br><br><strong>4. User Submissions </strong>
<br>A. The squareBracket Website may now or in the future permit the submission of videos or other communications submitted by you and other users ("User Submissions"), and the hosting, sharing and/or publishing of such User Submissions.  You understand that whether or not such User Submissions are published, squareBracket does not guarantee any confidentiality with respect to any submissions.  

<br><br>B. You shall be solely responsible for your own User Submissions and the consequences of posting or publishing them. In connection with User Submissions, you affirm, represent and/or warrant that: (i) you own, or have the necessary licenses, rights, consents, and permissions to use and authorize squareBracket to use, all patent, trademark, trade secret, copyright or other proprietary rights in and to any and all User Submissions to enable inclusion and use of the User Submissions in the manner contemplated by the Website and these Terms of Service; and (ii) you have the written consent, release, and /or permission of each and every identifiable individual person in the User Submission to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of the User Submissions in the manner contemplated by the Website and these Terms of Service.   For clarity, you shall retain all of your ownership rights in your User Submissions.  However, by submitting the User Submissions to squareBracket, you hereby grant squareBracket a worldwide, non-exclusive, fully paid-up, royalty-free, irrevocable, perpetual, sublicenseable and transferable license to use, reproduce, distribute, prepare derivative works of, display, perform and otherwise exploit the User Submissions in connection with the squareBracket Website and squareBracket's (and its successor's) business, including without limitation for promoting and redistributing part or all of the squareBracket Website (and derivative works thereof) in any media formats and through any media channels.  You also hereby grant each user of the squareBracket Website a non-exclusive license to access your User Submissions through the Website, and to use, reproduce, distribute, prepare derivative works of, display and perform such User Submissions as permitted through the functionality of the Website and under these Terms of Service, 

<br><br>C. In connection with User Submissions, you further agree that you will not: (i) submit material that is copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from their rightful owner to post the material and to grant squareBracket all of the license rights granted herein; (ii) publish falsehoods or misrepresentations that could damage squareBracket or any third party; (iii) submit material that is unlawful, obscene, defamatory, libelous, threatening, pornographic, harassing, hateful, racially or ethnically offensive or encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law or is otherwise inappropriate; (iv) post advertisements or solicitations of business: (v) impersonate another person. squareBracket does not endorse any User Submission or any opinion, recommendation or advice expressed therein, and squareBracket expressly disclaims any and all liability in connection with User Submissions. If notified by a user or a content owner of a User Submission that allegedly does not conform to this Agreement, squareBracket may investigate the allegation and determine in good faith and in its sole discretion whether to remove the User Submission, which it reserves the right to do at any time.  For clarity, squareBracket does not permit copyright infringing activities on its Website, and reserves the right to terminate access to the Website, and remove all Content submitted, by any persons who are found to be repeat infringers.

<br><br>D. In particular, if you are a copyright owner or an agent thereof, and believe that any User Submission infringes upon your copyrights, you may submit a notification pursuant to the Digital Millennium Copyright Act ("DMCA") by providing our Copyright Agent with the following information in writing: (a) the electronic or physical signature of the owner of the copyright or the person authorized to act on the owner's behalf; (b) identification of the copyrighted work(s) that you claim has been infringed; (c) identification of the specific User Submission(s) alleged to be infringing, including information reasonably sufficient to permit squareBracket to identify and locate the material on the squareBracket Website; (d) information reasonably sufficient to permit squareBracket to contact you, such as your name, address, telephone number, and email address; (e) a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and (f) a statement, made under penalty of perjury, that the above information in your notification is accurate and that you are the copyright owner or are authorized to act on the copyright owner's behalf. squareBracket's designated Copyright Agent to receive notifications of claimed infringement is: [copyright@youtube.com]  For clarity, only DMCA notices should go to the Copyright Agent; any other feedback, comments, requests for technical support and other communications should be directed to squareBracket customer service through http://www.youtube.com/contact.php.  You acknowledge that if you fail to comply with all of the requirements of this Section 5(D), your DMCA notice may not be valid.  

<br><br>E. You understand that when using the squareBracket Website you will be exposed to User Submissions from a variety of sources, and that squareBracket is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such User Submissions. You further understand and acknowledge that you may be exposed to User Submissions that are inaccurate, offensive, indecent or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against squareBracket with respect thereto, and agree to indemnify and hold squareBracket, its Owners/Operators, affiliates, and/or licensors, harmless to the fullest extent allowed by law regarding all matters related to your use of the site.   

<br><br>F. squareBracket permits you to link to Your own User Submissions hosted on the website or User Submissions of other third parties available on the Website, for personal, non-commercial purposes only.  In addition, squareBracket provides an "Embeddable Player" feature, in which you can incorporate certain User Submissions on your own personal, non-commercial websites, provided that you include a prominent link back to the squareBracket website on the pages containing the Embeddable Player.  You understand that the User Submissions, whether or not linked or embedded into other web sites, are provided to You only on an as-available basis, and squareBracket does not guarantee that their availability will be uninterrupted or bug free.  squareBracket reserves the right to discontinue any aspect to the squareBracket Website at any time, including discontinue any linked or embedded Content either generally or in specific cases.

<br><br><strong>5. Warranty Disclaimer</strong> 
<br>YOU AGREE THAT YOUR USE OF THE squareBracket WEBSITE SHALL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, squareBracket, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE WEBSITE AND YOUR USE THEREOF. squareBracket MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THIS SITE'S CONTENT OR THE CONTENT OF ANY SITES LINKED TO THIS SITE, AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR WEBSITE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR WEBSITE, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH OUR WEBSITE BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT, OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED OR OTHERWISE MADE AVAILABLE VIA THE SERVICE. squareBracket DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE squareBracket WEBSITE OR ANY HYPERLINKED WEBSITE, OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND squareBracket WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE. 

<br><br><strong>6. Limitation of Liability</strong> 
<br>IN NO EVENT SHALL squareBracket, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR WEBSITE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR WEBSITE, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH OUR WEBSITE BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT, OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED OR OTHERWISE MADE AVAILABLE VIA THE SERVICE, WHETHER BASED ON WARRANTY, CONTRACT, TORT OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT THE COMPANY IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION. 

<br><br>YOU SPECIFICALLY ACKNOWLEDGE THAT squareBracket SHALL NOT BE LIABLE FOR USER SUBMISSIONS OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY, AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU. 

<br><br>The Website is controlled and offered by Chaziz. The Website is hosted in it's facilities in the United States. Chaziz makes no representations that the squareBracket Website is appropriate or available for use in other locations.  Those who access or use the squareBracket Website from other jurisdictions do so at their own volition and are responsible for compliance with local law.

<br><br><strong>7. Indemnity</strong> 
<br>You agree to defend, indemnify and hold harmless squareBracket, its parent corporation, officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from: (i) your use of and access to the squareBracket Website; (ii) your violation of any term of this Agreement; (iii) your violation of any third party right, including without limitation any copyright, property, or privacy right; or (iv) any claim that one of your User Submissions caused damage to a third party. This defense and indemnification obligation will survive this Agreement and your use of the squareBracket Website. 

<br><br><strong>8. Ability to Accept Terms of Service</strong> 
<br>You affirm that you are over the age of 13, as the squareBracket Website is not intended for children under 13.  

</div>
<?php include("footer.php"); ?>